### PR TITLE
fix(dns-service): make search intuitive to use

### LINKED ISSUE #1203: Search in DNS view is unintuitive to use
When searching for a DNS zone the help text shows ``Search term can use wildcard "*".`` which suggests that you don't need to use wildcards to find something. In reality you need to pre- and suffix a search with wildcards to get the expected result.

For example if you search for ``global`` you would expect that to match ``global.example.com`` which is not the case unless you add the wildcards. Elektra should do that by default to make the search more end user friendly.

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Closes #1203

### CODE REVIEW

File: plugins/dns_service/app/controllers/dns_service/zones_controller.rb [hunk 1]
```diff
@@ -72,9 +73,10 @@ def show
 
       if params.include?(:search)
         if not params[:search].blank?
-          @search = params[:search]
+          @search = params[:search]
```
Comment (joker-at-work) [inline plugins/dns_service/app/controllers/dns_service/zones_controller.rb:76]: this adds a space at the end of the line

File: plugins/dns_service/app/controllers/dns_service/zones_controller.rb [hunk 2]
```diff
@@ -72,9 +73,10 @@ def show
 
       if params.include?(:search)
         if not params[:search].blank?
-          @search = params[:search]
+          @search = params[:search] 
           @searchfor = "#{params[:searchfor]}"
-          filter = { @searchfor.downcase() => @search }
+          # sourunding the user submitted search term with wildcards is stupid but the easiest way to make the search intuitive and match partial names
```
Comment (joker-at-work) [inline plugins/dns_service/app/controllers/dns_service/zones_controller.rb:78]: same typo as above

**Review by joker-at-work — COMMENTED** [review]
3 little nit-picks

File: plugins/dns_service/app/controllers/dns_service/zones_controller.rb (hunk 1 above)
Comment (VoigtS) [reply plugins/dns_service/app/controllers/dns_service/zones_controller.rb]: Thanks, this was a unnoticed leftover from testing.

File: plugins/dns_service/app/controllers/dns_service/zones_controller.rb [hunk 3]
```diff
@@ -74,7 +75,8 @@ def show
         if not params[:search].blank?
           @search = params[:search]
           @searchfor = "#{params[:searchfor]}"
-          filter = { @searchfor.downcase() => @search }
+          # surrunding the user submitted search term with wildcards is stupid but the easiest way to make the search intuitive and match partial names
```
Comment (edda) [inline plugins/dns_service/app/controllers/dns_service/zones_controller.rb:78]: Since we started nitpicking, this still isn't correct. A new typo appeared ;) 
```suggestion
          # surrounding the user submitted search term with wildcards is stupid but the easiest way to make the search intuitive and match partial names
```

**Review by edda — DISMISSED** [review]

File: plugins/dns_service/app/controllers/dns_service/zones_controller.rb [hunk 4]
```diff
@@ -18,7 +18,8 @@ def index
         if not params[:search].blank?
           @search = params[:search]
           @searchfor = "#{params[:searchfor]}"
-          filter = { @searchfor.downcase() => @search }
+          # surrounding the user submitted search term with wildcards is stupid but the easiest way to make the search intuitive and match partial names
+          filter = { @searchfor.downcase() => "*" + @search + "*" }
```
Comment (hgw77) [inline plugins/dns_service/app/controllers/dns_service/zones_controller.rb:22]: it is better to use `"*#{@search}*"` it should work the same way as `"*" + @search + "*"`

File: plugins/dns_service/app/controllers/dns_service/zones_controller.rb [hunk 5]
```diff
@@ -74,7 +75,8 @@ def show
...
```
Comment (hgw77) [inline plugins/dns_service/app/controllers/dns_service/zones_controller.rb:79]: same as above, it is better to use `"*#{@search}*"` instead of `"*" + @search + "*"`

**Review by andypf — APPROVED** [review]
Super!

**Review by hgw77 — APPROVED** [review]
